import Foundation
import MonitorCore
var count = 0
func expect<T: Equatable>(_ actual: T, _ expected: T, _ message: String) {
    count += 1
    guard actual == expected else {
        fputs("FAIL: \(message): \(actual) != \(expected)\n", stderr); exit(1)
    }
}
expect(NetworkStatus(latency: 99).color, .green, "below threshold")
expect(NetworkStatus(latency: 100).color, .yellow, "threshold inclusive")
expect(NetworkStatus(latency: 250).color, .yellow, "upper threshold inclusive")
expect(NetworkStatus(latency: 251).color, .red, "high latency")
expect(NetworkStatus(checked: true).title, "OFF", "unreachable")
expect(NetworkStatus().title, "--ms", "not checked")
var schedule = RecoverySchedule()
for (reachable, expected) in [(true,10.0),(false,3.0),(true,3.0),(false,3.0),(true,3.0),(true,3.0),(true,10.0)] {
    expect(schedule.interval(reachable: reachable), expected, "three consecutive recovery probes")
}
let legacy: [String: Any] = ["primary": ["usedPercent": 90, "windowDurationMins": 300], "secondary": ["usedPercent": 28, "windowDurationMins": 10080]]
expect(QuotaStatus.parse(["rateLimits": legacy])?.remainingPercent, 72, "weekly duration not position")
expect(QuotaStatus.parse(["rateLimits": ["secondary": ["usedPercent": 28]]]), nil, "unknown duration")
expect(QuotaStatus.parse(["rateLimits": legacy, "rateLimitsByLimitId": ["other": legacy]]), nil, "map precedence")
expect(QuotaStatus.parse(["rateLimitsByLimitId": ["codex": ["primary": ["usedPercent": 120, "windowDurationMins": 10080]]]])?.remainingPercent, 0, "lower clamp")
expect(QuotaStatus.parse(["rateLimits": ["primary": ["usedPercent": -5, "windowDurationMins": 10080]]])?.remainingPercent, 100, "upper clamp")
expect(QuotaStatus.parse(["rateLimits": ["limitId": "other", "secondary": ["usedPercent": 28, "windowDurationMins": 10080]]]), nil, "ignore noncodex event")
expect(QuotaStatus().title, "7D--", "missing quota")
let cached = QuotaStatus(remainingPercent: 72, updatedAt: Date(timeIntervalSince1970: 100), stale: true)
expect(try JSONDecoder().decode(QuotaStatus.self, from: JSONEncoder().encode(cached)), cached, "cache round trip")
print("PASS: \(count) assertions")

var store = ExecutionStore()
let old = ExecutionID(serverID: "A", threadID: "thread", turnID: "old")
let new = ExecutionID(serverID: "A", threadID: "thread", turnID: "new")
let other = ExecutionID(serverID: "B", threadID: "thread", turnID: "new")
store.upsert(MonitoredExecution(id: old, title: "Old"))
store.transition(old, to: .completed)
store.upsert(MonitoredExecution(id: new, title: "New"))
store.upsert(MonitoredExecution(id: other, title: "Other server"))
store.acknowledge(old)
expect(store.executions[new]?.state, .running, "old acknowledgement preserves new turn")
store.acknowledge(new)
expect(store.executions[new] != nil, true, "running cannot be acknowledged")
store.transition(new, to: .waitingDecision)
expect(store.sorted.first?.id, new, "decision has priority")
store.disconnected(server: "A")
expect(store.executions[new]?.state, .unknown, "disconnect invalidates state")
expect(store.executions[other]?.state, .running, "disconnect scoped to server")
store.transition(new, to: .failed)
store.upsert(MonitoredExecution(id: new, title: "Stale replay"))
expect(store.executions[new]?.state, .failed, "stale snapshot cannot resurrect completed turn")
let connection = UUID()
let decision = DecisionRequest(id: .init(execution: new, connection: connection, request: .string("9")), method: "item/commandExecution/requestApproval", params: ["availableDecisions": ["decline"]])
expect(decision.approval(allow: true) == nil, true, "unavailable approval not synthesized")
expect(decision.approval(allow: false)?["decision"] as? String, "decline", "decline exact wire value")
expect(RPCID.number(9) == RPCID.string("9"), false, "string and number IDs distinct")
let permission = DecisionRequest(id: decision.id, method: "item/permissions/requestApproval", params: ["permissions": ["network": ["enabled": true]]])
expect(permission.approval(allow: true)?["scope"] as? String, "turn", "never grant session implicitly")
expect((permission.approval(allow: false)?["permissions"] as? [String: Any])?.isEmpty, true, "deny permissions grants nothing")
var codec = WebSocketCodec()
expect(try codec.append(Data([0x01, 0x02, 0xE4])).count, 0, "partial websocket frame")
expect(try codec.append(Data([0xB8, 0x89, 0x00])).first?.0, 9, "ping during fragmented message")
let frames = try codec.append(Data([0x80, 0x01, 0xAD]))
expect(String(data: frames[0].1, encoding: .utf8), "中", "UTF8 spans frames")
let masked = [UInt8](WebSocketCodec.frame(Data("hello".utf8)))
expect(masked[1] & 0x80, 0x80, "client mask mandatory")
expect(String(bytes: masked.dropFirst(6).enumerated().map { $0.element ^ masked[2 + $0.offset % 4] }, encoding: .utf8), "hello", "client payload roundtrip")
var invalid = WebSocketCodec()
do { _ = try invalid.append(Data([0x81, 0x80])); fatalError("accepted masked server frame") } catch { count += 1 }
print("PASS: \(count) total assertions (state, quota, network, websocket)")

// V1 acceptance: recency order, replay immunity, foreground mode, naming and input secrecy.
let a = ExecutionID(serverID: "S", threadID: "a", turnID: "1")
let b = ExecutionID(serverID: "S", threadID: "b", turnID: "1")
var recent = ExecutionStore()
var older = MonitoredExecution(id: a, title: "older", startedAt: Date(timeIntervalSince1970: 1))
var newer = MonitoredExecution(id: b, title: "newer", startedAt: Date(timeIntervalSince1970: 2))
older.updatedAt = Date(timeIntervalSince1970: 20); newer.updatedAt = Date(timeIntervalSince1970: 10)
recent.upsert(older); recent.upsert(newer)
expect(recent.sorted.first?.id, a, "same state sorts by state-change recency")
recent.transition(a, to: .completed); recent.acknowledge(a); recent.upsert(older)
expect(recent.executions[a] == nil, true, "acknowledged turn cannot be replayed")
let foreground = AppState(isCodexForeground: true, executions: [newer], decisions: [], connected: true)
expect(foreground.showsDynamicArea, false, "foreground running tasks do not duplicate Codex")
expect(AppState(isCodexForeground: false, executions: [newer], decisions: [], connected: true).showsDynamicArea, true, "background tasks show")
newer.state = .failed
expect(AppState(isCodexForeground: true, executions: [newer], decisions: [], connected: true).showsDynamicArea, true, "foreground failure retained")
expect(TaskNaming.title(["name": "Chosen", "cwd": "/tmp/project"], fallback: "Task 1"), "Chosen", "title priority")
expect(TaskNaming.title(["gitInfo": ["repositoryUrl": "git@github.com:owner/repo.git"], "cwd": "/tmp/work"], fallback: "Task 1"), "repo", "repository priority")
expect(TaskNaming.title(["cwd": "/tmp/project"], fallback: "Task 1"), "project", "cwd fallback")
expect(TaskNaming.title([:], fallback: "Task 1"), "Task 1", "numbered fallback")
let secretPreview = InputPreview.text("fixture-password", selection: NSRange(location: 0, length: 0), secure: true)
expect(secretPreview.contains("password"), false, "secret not in preview")
expect(secretPreview.contains("•"), true, "secret preview masked")
let aroundCursor = InputPreview.text(String(repeating: "a", count: 100) + "中" + String(repeating: "z", count: 100), selection: NSRange(location: 101, length: 0), secure: false)
expect(aroundCursor.contains("中▏"), true, "long preview tracks actual cursor")
let session = InputSession(request: decision.id)
session.answer(question: "q1", text: "secret-fixture")
session.answer(question: "q2", text: "中文🚀")
expect(session.questionIndex, 2, "multi-question progress")
let answers = session.response()["answers"] as? [String: [String: [String]]]
expect(answers?["q2"]?["answers"], ["中文🚀"], "multi-question wire shape")
session.clear(); expect(session.isEmpty, true, "session clears owned buffers")
let explicitSession = DecisionRequest(id: decision.id, method: "item/fileChange/requestApproval", params: [:])
expect(explicitSession.approval(allow: true, forSession: true)?["decision"] as? String, "acceptForSession", "explicit session grant")
expect(decision.approval(allow: true, forSession: true) == nil, true, "session grant respects available choices")
print("PASS: \(count) total core assertions")

var metrics = ExecutionTelemetry()
expect(metrics.planFraction, nil, "missing plan is unknown, not zero progress")
expect(metrics.contextFraction, nil, "missing context is unknown")
metrics.updatePlan(["plan": [["step": "One", "status": "completed"], ["step": "Two", "status": "inProgress"]]])
expect(metrics.planFraction, 0.5, "step based progress")
metrics.updatePlan(["plan": [["step": "Replacement", "status": "pending"]]])
expect(metrics.completedSteps, 0, "plan revision replaces old steps")
metrics.updateUsage(["tokenUsage": ["last": ["totalTokens": 50], "total": ["totalTokens": 800], "modelContextWindow": 100]])
expect(metrics.contextFraction, 0.5, "context uses last call, not cumulative usage")
expect(metrics.totalTokens, 800, "cumulative usage separate")
metrics.updateUsage(["tokenUsage": ["last": ["totalTokens": 120], "total": ["totalTokens": 900], "modelContextWindow": 100]])
expect(metrics.contextFraction, 1, "context visual clamps at capacity")
metrics.updateUsage(["tokenUsage": ["last": ["totalTokens": -1], "modelContextWindow": 0]])
expect(metrics.contextFraction, nil, "invalid counters unknown")
metrics.updateItem(["id": "cmd", "type": "commandExecution", "command": "echo fixture"], completed: false)
metrics.updateItem(["id": "mcp", "type": "mcpToolCall", "server": "docs", "tool": "search"], completed: false)
expect(metrics.currentActivities.count, 2, "overlapping current tools")
metrics.updateItem(["id": "cmd", "type": "commandExecution"], completed: true)
expect(metrics.currentActivities.last?.tool, "docs.search", "completion removes only its tool")
metrics.updateItem(["id": "agents", "type": "collabAgentToolCall", "receiverThreadIds": ["a", "b"], "agentsStates": ["a": ["status": "running"], "b": ["status": "completed"]]], completed: true)
metrics.updateItem(["id": "again", "type": "collabAgentToolCall", "receiverThreadIds": ["a"], "agentsStates": ["a": ["status": "interrupted"]]], completed: true)
expect(metrics.agents.count, 2, "agents deduplicated by thread identity")
expect(metrics.activeAgents, 0, "interrupted agent is not active")
metrics.disconnect()
expect(metrics.currentActivities.isEmpty, true, "disconnect does not claim old tools are running")
expect(metrics.agentsStale && metrics.contextStale && metrics.planStale, true, "retained telemetry marked last known")
metrics.updatePlan(["plan": []])
expect(metrics.planStale == false && metrics.contextStale, true, "plan event does not freshen context")
var pausedStore = ExecutionStore()
pausedStore.upsert(MonitoredExecution(id: old, title: "Paused", state: .paused))
pausedStore.disconnected(server: "A")
expect(pausedStore.executions[old]?.state, .paused, "confirmed pause survives disconnect")
print("PASS: \(count) total core assertions including telemetry")

var desktop = DesktopSnapshot()
try desktop.apply(["type": "snapshot", "revision": 10, "conversationState": ["requests": [], "turnHistory": ["history": ["entitiesByKey": ["old": ["turnId": "old", "turnStartedAtMs": 1.0], "new": ["turnId": "new", "turnStartedAtMs": 2.0]]]]]])
expect(desktop.latestTurn?["turnId"] as? String, "new", "desktop selects execution by start time, not dictionary order")
try desktop.apply(["type": "patches", "baseRevision": 10, "revision": 11, "patches": [["op": "add", "path": ["requests", 0], "value": ["id": "request-1"]]]])
expect((desktop.state["requests"] as? [[String: Any]])?.count, 1, "desktop inserts pending request")
do { try desktop.apply(["type": "patches", "baseRevision": 9, "revision": 12, "patches": []]); fatalError("out of order revision accepted") } catch { count += 1 }
expect(desktop.revision, 11, "revision gap leaves snapshot untouched")
do { try desktop.apply(["type": "patches", "baseRevision": 11, "revision": 12, "patches": [["op": "remove", "path": ["requests", 99]]]]); fatalError("invalid patch accepted") } catch { count += 1 }
expect((desktop.state["requests"] as? [[String: Any]])?.count, 1, "invalid patch is atomic")
try desktop.apply(["type": "patches", "baseRevision": 11, "revision": 12, "patches": [["op": "remove", "path": ["requests", 0]]]])
expect((desktop.state["requests"] as? [[String: Any]])?.count, 0, "request removal clears pending state")
print("PASS: \(count) total core assertions including desktop revision reconciliation")

var titleSnapshot = DesktopSnapshot()
try titleSnapshot.apply(["type": "snapshot", "revision": 1, "conversationState": ["title": "", "generatedTitle": "Generated task"]])
expect(titleSnapshot.displayTitle, "Generated task", "empty desktop title falls back to generated title")
try titleSnapshot.apply(["type": "snapshot", "revision": 2, "conversationState": ["title": "  ", "generatedTitle": ""]])
expect(titleSnapshot.displayTitle, "Codex task", "empty metadata never renders only a status icon")
try titleSnapshot.apply(["type": "snapshot", "revision": 3, "conversationState": ["title": "Named later", "generatedTitle": "Generated task"]])
expect(titleSnapshot.displayTitle, "Named later", "later explicit title takes precedence")
print("PASS: \(count) total core assertions including desktop title fallbacks")

var asyncSnapshot = DesktopSnapshot()
let asyncItem: [String: Any] = ["id": "fixture-question", "type": "agentMessage", "delivery": "async",
    "questions": [["title": "Choose a branch", "options": ["Alpha", "Beta"]], ["title": "Describe it"]]]
func asyncState(_ items: [[String: Any]], status: String = "inProgress", flags: [String] = []) -> [String: Any] {
    ["requests": [], "threadRuntimeStatus": ["type": "active", "activeFlags": flags],
     "turns": [["turnId": "turn-async", "status": status, "items": items]]]
}
try asyncSnapshot.apply(["type": "snapshot", "revision": 1, "conversationState": asyncState([asyncItem])])
expect(asyncSnapshot.pendingAsyncQuestions.count, 2, "async questions discovered outside requests")
expect(asyncSnapshot.isWaitingForUser, true, "async question is waiting despite active turn")
let asyncQuestion = asyncSnapshot.pendingAsyncQuestions[0]
let asyncID = asyncQuestion["id"] as! String
expect(asyncID, "[\"request_user_input_async\",\"fixture-question\",0]", "exact desktop async identity")
expect((asyncQuestion["options"] as? [[String: String]])?.first?["label"], "Alpha", "preserve selectable labels")
let reply = DesktopSnapshot.asyncReply(questions: [asyncQuestion], result: ["answers": [asyncID: ["answers": ["Beta"]]]])!
expect(reply.contains("Beta"), true, "encode selected response")
expect(DesktopSnapshot.asyncReply(questions: [asyncQuestion], result: ["answers": [:]]), nil, "reject missing answer")
let acceptedReply: [String: Any] = ["type": "steeringUserMessage", "status": "accepted", "input": [["type": "text", "text": reply]]]
try asyncSnapshot.apply(["type": "snapshot", "revision": 2, "conversationState": asyncState([asyncItem, acceptedReply])])
expect(asyncSnapshot.pendingAsyncQuestions.count, 1, "accepted reply clears only its question")
var pendingReply = acceptedReply; pendingReply["status"] = "pending"
try asyncSnapshot.apply(["type": "snapshot", "revision": 3, "conversationState": asyncState([asyncItem, pendingReply])])
expect(asyncSnapshot.pendingAsyncQuestions.count, 2, "unconfirmed send stays waiting")
try asyncSnapshot.apply(["type": "snapshot", "revision": 4, "conversationState": asyncState([asyncItem], status: "completed")])
expect(asyncSnapshot.pendingAsyncQuestions.count, 0, "completed turn has no actionable async questions")
try asyncSnapshot.apply(["type": "snapshot", "revision": 5, "conversationState": asyncState([], flags: ["waitingOnUserInput"])])
expect(asyncSnapshot.isWaitingForUser, true, "runtime waiting flag without request still warns")
print("PASS: \(count) total core assertions including asynchronous questions")
