#!/usr/bin/env python3
"""Prepare local release metadata/Cask from the already-built configured builder artifact; never publishes."""
import hashlib
import json
import pathlib
import plistlib
import subprocess
import zipfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
subprocess.run(['python3', str(ROOT / 'scripts/check_build_host.py')], check=True)
info = plistlib.loads((ROOT / 'Resources/Info.plist').read_bytes())
version = info['CFBundleShortVersionString']
artifact = ROOT / 'dist/CodexTouchBarMonitor-arm64.zip'
with zipfile.ZipFile(artifact) as archive:
    names = archive.namelist()
    assert 'CodexTouchBarMonitor.app/Contents/MacOS/CodexTouchBarMonitor' in names
    assert not any('/._' in name or name.startswith('__MACOSX/') for name in names)
    packaged = plistlib.loads(archive.read('CodexTouchBarMonitor.app/Contents/Info.plist'))
    assert packaged['CFBundleShortVersionString'] == version
sha = hashlib.sha256(artifact.read_bytes()).hexdigest()
repository = 'Luyzr/CodexTouchBarMonitor'
url = f'https://github.com/{repository}/releases/download/v{version}/{artifact.name}'
manifest = dict(version=version, tag=f'v{version}', repository=repository, asset=artifact.name,
                sha256=sha, url=url, published=False,
                sourceCommit=subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=ROOT, text=True).strip(),
                sourceDirty=bool(subprocess.check_output(['git', 'status', '--porcelain'], cwd=ROOT)))
(ROOT / 'dist/release-manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
(ROOT / 'dist/SHA256SUMS').write_text(f'{sha}  {artifact.name}\n')
cask = f'''# Generated by prepare_release.py. Publish the matching release before distribution.
cask "codex-touchbar-monitor" do
  version "{version}"
  sha256 "{sha}"
  url "{url}"
  name "Codex TouchBar Monitor"
  desc "Background Codex task and decision monitor for macOS"
  homepage "https://github.com/{repository}"
  depends_on arch: :arm64
  depends_on macos: ">= :ventura"
  app "CodexTouchBarMonitor.app"
  zap trash: "~/Library/Preferences/io.local.CodexTouchBarMonitor.plist"
end
'''
(ROOT / 'dist/codex-touchbar-monitor.rb').write_text(cask)
print(f'Prepared v{version}: validated archive, SHA256SUMS, release-manifest.json and Homebrew Cask')
